stages:
  - clean
  - build
  - deploy

clean-job:
  stage: clean
  script:
    - docker rm -f 01-product-v1
    - docker rmi -f 01-product-v1
    - cd product
    - mvn clean

build-job:
  stage: build
  script:
    - mvn package -DskipTests=true
    - mv target/product-1.0.0.jar 01-product-v1.jar
    - docker build -t 01-product-v1 .
    - rm 01-product-v1.jar

deploy-job:
  stage: deploy
  script:
    - docker run -di --network unbownow_default --name 01-product-v1 -p 8601:8080 -e TZ=America/Los_Angeles 01-product-v1
